### ISSUE TITLE
How to catch 404 Not Found APIRequests?

### ISSUE THREAD

**Issue by EricBatlle** [ZeShmoutt/Blizzard-API-For-Unity#4]
There is a way to do something if API request fails/can't find results? To perform something like:

```
StartCoroutine(BlizzardAPI.WowProfile.GetCharacterProfileSummary(BattleNetRegion.Europe, "zuljin", "abronto", action_Result: (result) =>
{
    if(result == null)
    {
        Debug.Log("Character doesn't exist");
    }
    else
    {
        Debug.LogFormat(result.character_class.name.es_ES);
    }
}));
```

Seems like `BlizzardAPI.APIRequest` only have a `Debug.LogError`, am I missing something? Thanks

**Comment by ZeShmoutt** [comment]
As you said, there's no way to handle that case, and it should definitely be something more than just an error message.

I'll check what I can do tomorrow.

**Comment by EricBatlle** [comment]
Thanks @ZeShmoutt , if it helps, that's my quick-fix for the moment:

Instead of 

```
else
{
      Debug.LogError("<color=red>Error : </color>" + request.error);
}
```
I use 

```
else
{
    action_Result(null);
    Debug.Log("<color=red>Error : </color>" + request.error);
}       
```

So I know if the result of the API is null, something went wrong, also I've changed LogError to Log, cause LogError freeze execution.

**Comment by ZeShmoutt** [comment]
I'll try to see if I can add some kind of `action_ifError` without bloating function calls more than they already are.

> LogError freeze execution

![image](https://user-images.githubusercontent.com/36408045/94662181-5411b380-0308-11eb-9279-38c0786205d3.png)

**Comment by EricBatlle** [comment]
> > LogError freeze execution
> 
> ![image](https://user-images.githubusercontent.com/36408045/94662181-5411b380-0308-11eb-9279-38c0786205d3.png)

:O thanks

**Comment by ZeShmoutt** [comment]
Added an `action_onError` callback in release 1.11.0.
