### ISSUE TITLE
Serialization depth loop

### ISSUE THREAD

**Issue by EricBatlle** [ZeShmoutt/Blizzard-API-For-Unity#8]
On **Endpoint_WoW_GameData_JournalEncounter.cs** there is what it seems to me like a serialization depth loop, this will trigger Unity-warnings and stop the call as it only allow to serialize 7 depth levels.

Concretly the problem is the `JournalSection `structure used in `sections` variable:
```
[Serializable]
public struct JournalSection
{
	public int id;
	public LocalizedString title;
	public LocalizedString body_text;
	public RefIdStruct creature_display;
	public JournalSection[] sections;
}
public JournalSection[] sections;
```
The easiest way to fix that (that I know) is mark as `NonSerialized `the sections variable inside JournalSectino, so the struct will look like:

```
[Serializable]
public struct JournalSection
{
	public int id;
	public LocalizedString title;
	public LocalizedString body_text;
	public RefIdStruct creature_display;
	[NonSerialized] public JournalSection[] sections;
}
```

I can make a PR but as you pointed in https://github.com/ZeShmoutt/Blizzard-API-For-Unity/issues/6 maybe your custom editor stuff is also better in this case.

Hope it helps! ^^

**Comment by ZeShmoutt** [comment]
This is more of a problem about Unity's serialization than something else.

It's normal that journal encounters have sections in sections in sections ([Firelands Ragnaros](https://buyyourproduct.com/wp-content/uploads/Dungeon-Guides-1.png) is a good example), but unless Blizzard really fucked up their data it shouldn't make a loop.

On the other hand, as you saw, Unity just can't serialize that deep. Sadly, you're proprably better off using the raw JSON for that specific case.

Out of curiosity, which boss did you search that requires to go 7 sections deep ?

**Comment by EricBatlle** [comment]
Seems like is no boss-specific problem.

What I'm trying to do is the following:
```
StartCoroutine(BlizzardAPI.WowGameData.GetJournalEncounter(89, (journalEncounter)=> 
{	
}, null, null, null, BattleNetRegion.Europe));
```
With the following warning:

```
Serialization depth limit 7 exceeded at 'JournalSection.sections'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
8: JournalSection.sections
7: JournalSection.sections
6: JournalSection.sections
5: JournalSection.sections
4: JournalSection.sections
3: JournalSection.sections
2: JournalSection.sections
1: JournalSection.sections
0: ZeShmouttsAssets.BlizzardAPI.JSON::Json_Wow_JournalEncounter.sections

UnityEngine.JsonUtility:FromJson(String)
ZeShmouttsAssets.BlizzardAPI.<>c__DisplayClass30_0`1:<SendRequest>b__0(String) (at Library/PackageCache/com.zeshmouttsassets.blizzardapi@b1a2d56235/Scripts/_Core/BlizzardAPI.cs:88)
ZeShmouttsAssets.BlizzardAPI.<APIRequest>d__36:MoveNext() (at Library/PackageCache/com.zeshmouttsassets.blizzardapi@b1a2d56235/Scripts/_Core/BlizzardAPI.cs:239)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by ZeShmoutt** [comment]
I tried retrieving that encounter with the API tester tool included in the package, and got pretty much the same warning. The json export seems to have worked though, and I don't think I see anything weird in it, it only goes 3-4 sections deep.

Going with `[NonSerialized]` could work, but then it gets annoying to work with because it's not serialized.

From what I saw with a quick look on Google it's just a warning to say "you might have an infinite loop on your hands here", so you can also ignore the warning I guess ?

**Comment by EricBatlle** [comment]
I think that you [can't disable the warning](https://answers.unity.com/questions/1402455/recursive-serialization-manual-limit.html) and ignore it is error-prone, no?

Seems that the struct should have some identifier, and this identifier is the stuff to serialize? :S
